variables:
  REPO: gitlab.com

stages:
  - build
  - test

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags: 
    - build
    - gitlab-runner
  script: 
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t app .
    # - ./bin/blog

test:
  stage: test
  image: golang:alpine
  services:
    - cockroachdb/cockroach:latest
  variables:
    DB_USER: root
    DB_HOST: cockroachdb
    DB_NAME: blog-api
    DB_PORT: 26257
    DB_SSL_MODE: disable
  tags: 
    - gitlab-runner
  script: 
    - go install github.com/cucumber/godog/cmd/godog@v0.12.5
    - CGO_ENABLED=0 GOOS=linux godog run 
    
