image: golang:alpine

variables:
  REPO: gitlab.com

stages:
  - build
  - test

# before_script:
#   - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
#   - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
#   - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
#   - go get -v -d ./...


build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags: 
    - build
    - gitlab-runner
  script: 
    - echo -n $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t app .
    # - ./bin/blog

test:
  stage: test
  tags: 
    - gitlab-runner
  script: 
    # - go test ./...
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

