image: golang:1.17-alpine

variables:
  REPO: gitlab.com

stages:
  - build
  - test

# before_script:
#   - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
#   - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
#   - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
#   - go get -v -d ./...


build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags: 
    - build
    - gitlab-runner
  script: 
    - docker build -t app .
    # - ./bin/blog

test:
  stage: test
  tags: 
    - gitlab-runner
  script: 
    - go test ./...
